// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"layout/app"
	"layout/configs"
	"layout/internal/app/article/application"
	"layout/internal/app/article/interfaces/grpc"
	"layout/internal/app/article/interfaces/http"
	"layout/internal/app/article/repository"
)

// Injectors from wire.go:

// initApp init application.
func initApp(conf *configs.Configuration) *app.App {
	articleRepository := repository.NewArticle(conf)
	article := application.NewArticleUseCase(articleRepository)
	server := http.NewHTTPServer(article, conf)
	grpcServer := grpc.NewGrpcServer(article, conf)
	appApp := newApp(server, grpcServer)
	return appApp
}
