// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"layout/app"
	"layout/configs"
	"layout/internal/app/user/application"
	"layout/internal/app/user/interfaces/grpc"
	"layout/internal/app/user/repository"
)

// Injectors from wire.go:

// initApp init application.
func initApp(conf *configs.Configuration) *app.App {
	userRepository := repository.NewUser(conf)
	user := application.NewUserUseCase(userRepository)
	grpcServer := grpc.NewGrpcServer(user, conf)
	appApp := newApp(grpcServer)
	return appApp
}
